title = "stuff"
default_file = "main.kcl"

[settings.app]
[settings.meta]
id = "9aaddd6b-6da9-4ff2-b905-3629a26ea046"

[settings.modeling]
[cloud."zoo.dev"]
project_id = "9b866bf2-c314-4bc0-94ab-b958aeefbd9a"
